#!/bin/bash
set -e 

# make lintian happy
. /usr/share/debconf/confmodule
db_stop


if ! getent passwd kiosk-browser >/dev/null; then
    useradd --system --user-group --comment "Kiosk Browser User" --no-create-home --home-dir /var/lib/kiosk-browser kiosk-browser
    mkdir -p /var/lib/kiosk-browser
fi

# disable lightdm and enable nodm
echo "/usr/sbin/nodm" >/etc/X11/default-display-manager

# disable X cursor
sed -i -e 's/NODM_X_OPTIONS=.*/NODM_X_OPTIONS="-nocursor -nolisten tcp"/' -e 's/NODM_ENABLED=.*/NODM_ENABLED=true/' -e 's/NODM_USER=.*/NODM_USER=kiosk-browser/' /etc/default/nodm

# allow kiosk user to only write in directories needed by chromium
mkdir -p /var/lib/kiosk-browser/{.cache,.config/chromium,.pki}
chown -R kiosk-browser:kiosk-browser /var/lib/kiosk-browser/{.cache,.config/chromium,.pki}


# if lightdm is running stop if first
if status lightdm ; then
    stop lightdm || :
    sleep 5 # give it a moment to stop everything
fi

if pgrep -u kiosk-browser >/dev/null ; then
    service nodm stop || :
    echo "Waiting for kiosk-browser processes to exit..."
    sleep 20 # wait for chromium and other subprocesses to exit
fi

# always start nodm
service nodm start
