#!/bin/sh
set -e 

if ! getent passwd kiosk-browser >/dev/null; then
        adduser --disabled-password --gecos "Kiosk Browser User" --firstuid 200 --lastuid 300 --home /var/lib/kiosk-browser kiosk-browser
fi

# disable lightdm and enable nodm
echo "/usr/sbin/nodm" >/etc/X11/default-display-manager
sed -i -e 's/NODM_ENABLED=.*/NODM_ENABLED=true/' -e 's/NODM_USER=.*/NODM_USER=kiosk-browser/' /etc/default/nodm

# allow kiosk user to only write in chromium directories
mkdir -p /var/lib/kiosk-browser/{.cache/chromium,.cache/config,.pki}
chown -R kiosk-browser:kiosk-browser /var/lib/kiosk-browser/{.cache/chromium,.cache/config,.pki}
