#!/bin/bash
set -e

case "$1" in
    purge)
        if getent passwd kiosk-browser >/dev/null; then
             userdel --force --remove kiosk-browser || echo "Could not remove kiosk-browser user."
        fi
    ;;
    *)
        : do nothing
    ;;
esac
