#!/bin/sh
set -e

if getent passwd kiosk-browser-g >/dev/null; then
      	if [ -x /usr/sbin/deluser ]; then
        	deluser --remove-home kiosk-browser || echo "Could not remove kiosk-browser user."
	fi
fi
