#!/bin/bash
set -e

case "$1" in
    purge)
        if getent passwd kiosk-browser >/dev/null; then
             userdel --force --remove kiosk-browser || echo "Could not remove kiosk-browser user."
        fi
        if [ -e /usr/share/debconf/confmodule ]; then
                . /usr/share/debconf/confmodule
                db_purge
        fi
        rm -f /usr/sbin/kiosk-browser

    ;;
    *)
        : do nothing
    ;;
esac
